version: "3.8"

services:
  back:
    build: .
    container_name: backend
    expose:
      - 8000 
  
  front:
    build: ./todofront
    container_name: frontend
    ports:
     - 80:80
    depends-on:
     - backend 
