version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    expose:
      - 8000 
  
  frontend:
    build: ./todofront
    container_name: frontend
    ports:
     - 8080:80
    depends_on:
     - backend 
